services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}       # Substitutes value from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orders_system_network

volumes:
  postgres_data:

networks:
  orders_system_network:
    driver: bridge
